test:
	python test_solution.py
	cat data/1.in | python3 solution.py | diff - data/1.ans
	cat data/2.in | python3 solution.py | diff - data/2.ans
	cat data/3.in | python3 solution.py | diff - data/3.ans
	echo "All Kattis sample test cases passed!"